version: '3.1'

services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    restart: always
    ports:
      - "3333:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe

  app:
    image: nikitkamzgb/sensors 
    container_name: sensors-app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8888:8888"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?autoreconnect=true
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qwe
      SPRING_JPA_HIBERNATE_DDL_AUTO: update